#ifndef HTTN_H
#define HTTN_H

#define MSG_ID_SET_CFG 1
#define MSG_ID_GET_CFG 2
#define MSG_ID_OTA_APP 3        //Update app
#define MSG_ID_REMOVE_APP 4     //Remove app
#define MSG_ID_DEBUG_INFO 5


#define MSG_ID_PING 10
#define MSG_ID_REP_PING 11
#define MSG_ID_JOIN_ROOM_CMD 12
#define MSG_ID_EXIT_ROOM_CMD 13
#define MSG_ID_AUDIO_SCHEDULE_CONFIG 14
#define MSG_ID_AUDIO_EVENT_CONFIG 15
#define MSG_ID_AUDIO_EVENT_TRIGGER 17
#define MSG_ID_MASTER_WAKE_UP 16
#define CONFIG_REMOVE_MEET_GROUP_ID 99
#define CONFIG_VS_SPEAKER_WORKING_MODE 101
#define CONFIG_VS_SPEAKER_FM_FREQ1 102
#define CONFIG_VS_SPEAKER_FM_FREQ2  103
#define CONFIG_VS_SPEAKER_FM_FREQ3  104
#define CONFIG_VS_SPEAKER_SPK_DETECT  105
#define CONFIG_VS_SPEAKER_ADB_TCPIP 106
#define CONFIG_VS_SPEAKER_RELAY_DELAY_ON 107
#define CONFIG_VS_SPEAKER_RELAY_DELAY_OFF1 108
#define CONFIG_VS_SPEAKER_RELAY_DELAY_OFF2 109
#define CONFIG_VS_SPEAKER_FM_WORKING_FREQ 111
#define CONFIG_VS_SPEAKER_WIFINAME 112
#define CONFIG_VS_SPEAKER_WIFIPASS 113
#define CONFIG_VS_SPEAKER_WIFI_ENABLE 114
#define CONFIG_VS_SPEAKER_LCD_NEXTION_ENABLE 115
#define CONFIG_DELETE_WIFI_NAME 1010
#define CONFIG_RESTART_APP 1111
#define CONFIG_SAFE_REBOOT 2222
#define CONFIG_SAFE_SHUTDOWN 3333
#define CONFIG_EMERGENCY_REBOOT 4444
#define CONFIG_EMERGENCY_SHUTDOWN 5555

#define MSG_ID_EVENT 6
#define MODE_FM_FREQ1 11
#define MODE_FM_FREQ2 12
#define MODE_FM_FREQ3 13
#define CONFIG_MQTT_SRV 69

#define STREAM_IDLE 0
#define STREAM_PREPAIR  1
#define STREAM_BUFFERING  2
#define STREAM_PLAYING  3
#define STREAM_STOP  4
#define STREAM_ERROR  5

//Stream
#define MSG_ID_STREAM_COMMAND 18
#define CONFIG_MEET_VOLUME_PERCENT 96

//Các mã lệnh điều khiển stream cmdCode:
//Mức ưu tiên của lệnh stream emergencyLevel:
// 0 - stream bình thường, 1 - khẩn cấp mức 1, 2 - khẩn cấp mức 2 …
#define CMD_STREAM_PREPAIR 1
#define CMD_STREAM_START 2
#define CMD_STREAM_RUNNING 3
#define CMD_STREAM_STOP 4

//Thiết lập các thông tin cho thiết bị: name, group...
#define MSG_ID_DEVICE_CONFIG 100
//Cài đặt thông tin master stream http theo lịch
#define MSG_ID_MASTER_INFO_CONFIG 101
#define CONFIG_CONNECT_NEW_WIFI 1002
#define CONFIG_CONNECT_WIFI 1000
#define EVT_CODE_PWR_LOST 1

#endif